### ISSUE TITLE
Bot is randomly renaming channel names

### ISSUE THREAD

**Issue by MarcelCoding** [Defelo/MorpheusHelper#104]
**Describe the bug**
I was with some other people in a voice channel. (`talk-2`)
Then the people of `talk-1` left the channel and the bot renamed `talk-2` to `talk-1`.
That's not good because in the first moment i didn't found the according text channel.

**To Reproduce**
1. Say Person 1 to create a public voice channel
2. Say Person 2 to create a public voice channel
1. Say Person 1 to leave the created voice channel

**Expected behavior**
The bot should **NOT** rename the channel names after they are already created.

**Screenshots**

**Your Configuration (please complete the following information):**
- MorpheusHelper v2.0.3-6-gc38fc8c
- ask MrBlack#8359

**Comment by Defelo** [comment]
works as intended (for now). the voice channel system will be changed in a future version anyway.

**Comment by MarcelCoding** [comment]
Ok, thanks for your fast reply
