### ISSUE TITLE
Discordpy RTFM command

### ISSUE THREAD

**Issue by pohlium** [Defelo/MorpheusHelper#85]
As there is a lot of help for [discordpy](https://discordpy.readthedocs.io/) happening in the server, i thought it could be useful to have a command that allows us to query the documentation. For this purpose, i have already "built" [a cog in my own bot](https://gitlab.com/pohlium/jabkingdom-discordbot/-/blob/master/cogs/rtfm.py), which is a modified old version of [RoboDannys rtfm cog](https://github.com/Rapptz/RoboDanny/blob/17455c1bbad3cb4b3bc1483d3554c0b47a18e5b4/cogs/api.py).

As this has originally been released under the MIT license, i believe we should be allowed to use it in this project?
Would this in principle be acceptable? If so i'm happy to create a PR with the code and potentially a better command name so its not as generic as it is in my bot.

**Comment by pohlarized** [comment]
Looks like this btw
![image](https://user-images.githubusercontent.com/24480574/145727204-fe4b1af2-1733-45bd-9ff9-4c4171921000.png)

essentially gives you the searchbox functionality with the top 5 results from the docs matching your query

**Comment by Defelo** [comment]
I don't think there should be any problems regarding the license. When this command is executed, please include the name of the executing user in the footer (just like in the metaquesion cog).
